apiVersion: v2
name: status-monitor
description: FQDN status monitor (Flask + SQLite) com Nmap -sn e traceroute
type: application
version: 0.1.0
appVersion: "0.2"
home: https://quay.io/repository/fcalomen/status-monitor
keywords:
  - network
  - monitor
  - nmap
  - traceroute
  - openshift
maintainers:
  - name: status-board
